### PR TITLE
Check python3

### PR DESCRIPTION
**Pull request by alienzj**
I test code in python3 branch, so push to python3 branch.

### CODE REVIEW

**Comment by AlphaSquad** [comment]
Thank you very much for your contribution! 
I will test and pull your changes as soon as possible.

**Comment by alienzj** [comment]
Maybe CAMISIM need refactor, the code is not easy to read.

**Comment by alienzj** [comment]
There are so many wrapper code.

**Comment by AlphaSquad** [comment]
Yes, CAMISIM is a grown system and a lot of people have worked on it over the years and this shows. A major refactor is on my todo list, but it isn't very high up admittedly.

**Pull request closed without merging**
